const foodItem = [
{
  name: 'Phở Bò',
  category: 'phở',
  rating: 4.3,
  price: 30,
  img: 'img/phở/PhoBo.png',
  quantity: 1,
},
{
  name: 'Phở Gà',
  category: 'phở',
  rating: 4.3,
  price: 35,
  img: 'img/phở/PhoGa.png',
  quantity: 1,
},
{
  name: 'Phở Bò Gân',
  category: 'phở',
  rating: 4.3,
  price: 30,
  img: 'img/phở/PhoBoGan.png',
  quantity: 1,
},
{
  name: 'Phở Bò Viên',
  category: 'phở',
  rating: 4.3,
  price: 30,
  img: 'img/phở/PhoBoVien.png',
  quantity: 1,
},
{
  name: 'Cơm Bò Bít Tết',
  category: 'cơm',
  rating: 4.3,
  price: 30,
  img: 'img/cơm/ComBoBitTet.png',
  quantity: 1,
},
{
  name: 'Cơm Cà Ri',
  category: 'cơm',
  rating: 4.3,
  price: 30,
  img: 'img/cơm/ComCaRi.png',
  quantity: 1,
},
{
  name: 'Cơm Gà Xối Mỡ',
  category: 'cơm',
  rating: 4.3,
  price: 30,
  img: 'img/cơm/ComGaXoiMo.png',
  quantity: 1,
},
{
  name: 'Cơm Sườn',
  category: 'cơm',
  rating: 4.3,
  price: 30,
  img: 'img/cơm/ComSuon.png',
  quantity: 1,
},
{
  name: 'Cơm Xá Xíu',
  category: 'cơm',
  rating: 4.3,
  price: 30,
  img: 'img/cơm/ComXaXiu.png',
  quantity: 1,
},
{
  name: 'Hủ Tiếu Bò Viên',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 30,
  img: 'img/hủ tiếu/hutieubovien.png',
  quantity: 1,
},
{
  name: 'Hủ Tiếu Bò Kho',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 30,
  img: 'img/hủ tiếu/hutieubokho.png',
  quantity: 1,
},
{
  name: 'Hủ Tiếu Giò Heo',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 30,
  img: 'img/hủ tiếu/hutieugioheo.png',
  quantity: 1,
},
{
  name: 'Hủ Tiếu Thịt',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 30,
  img: 'img/hủ tiếu/hutieuthit.png',
  quantity: 1,
},
{
  name: 'Hủ Tiếu Xương',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 30,
  img: 'img/hủ tiếu/hutieuxuong.png',
  quantity: 1,
},
{
  name: 'Mì Khô',
  category: 'mì',
  rating: 4.3,
  price: 30,
  img: 'img/mì/mikho.png',
  quantity: 1,
},
{
  name: 'Mì Xá Xíu',
  category: 'mì',
  rating: 4.3,
  price: 30,
  img: 'img/mì/mixaxiu.jpg',
  quantity: 1,
},
{
  name: 'Mì Trứng',
  category: 'mì',
  rating: 4.3,
  price: 30,
  img: 'img/mì/mitrung.png',
  quantity: 1,
},
{
  name: 'Mì Xương',
  category: 'mì',
  rating: 4.3,
  price: 30,
  img: 'img/mì/mitrung.png',
  quantity: 1,
},
{
  name: 'Mì Bò Viên',
  category: 'mì',
  rating: 4.3,
  price: 30,
  img: 'img/mì/mibovien.png',
  quantity: 1,
},
{
  name: 'Mì Xào Hải Sản',
  category: 'mì',
  rating: 4.3,
  price: 30,
  img: 'img/mì/mixaohaisan.png',
  quantity: 1,
},
{
  name: 'Bánh Mì Bò Lá Lốt',
  category: 'bánh mì',
  rating: 4.3,
  price: 30,
  img: 'img/bánh mì/BanhMiBoLaLot.png',
  quantity: 1,
},
{
  name: 'Bánh Mì Gà',
  category: 'bánh mì',
  rating: 4.3,
  price: 30,
  img: 'img/bánh mì/BanhMiGa.png',
  quantity: 1,
},
{
  name: 'Bánh Mì Heo Quay',
  category: 'bánh mì',
  rating: 4.3,
  price: 30,
  img: 'img/bánh mì/BanhMiHeoQuay.png',
  quantity: 1,
},
{
  name: 'Bánh Mì Thịt Chả',
  category: 'bánh mì',
  rating: 4.3,
  price: 30,
  img: 'img/bánh mì/BanhMiThitCha.png',
  quantity: 1,
},
{
  name: 'Bánh Mì Xíu Mại',
  category: 'bánh mì',
  rating: 4.3,
  price: 30,
  img: 'img/bánh mì/BanhMiXiuMai.png',
  quantity: 1,
},
{
  name: 'Bánh Mì Xúc xích',
  category: 'bánh mì',
  rating: 4.3,
  price: 30,
  img: 'img/bánh mì/BanhMiXucXich.png',
  quantity: 1,
},
{
  name: 'Bánh Xèo Chay',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 30,
  img: 'img/đồ ăn chay/BanhXeoChay.png',
  quantity: 1,
},
{
  name: 'Chả Giò Chay',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 30,
  img: 'img/đồ ăn chay/ChaGioChay.png',
  quantity: 1,
},
{
  name: 'Đậu Phụ Chiên',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 30,
  img: 'img/đồ ăn chay/DauPhuChien.png',
  quantity: 1,
},
{
  name: 'Gỏi Cuốn Chay',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 30,
  img: 'img/đồ ăn chay/GoiCuonChay.png',
  quantity: 1,
},
{
  name: 'Khoai Tây Nghiền Salad',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 30,
  img: 'img/đồ ăn chay/KhoaiTayNghienSalad.png',
  quantity: 1,
},
{
  name: 'Màn Thầu',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 30,
  img: 'img/đồ ăn chay/ManThau.png',
  quantity: 1,
},
{
  name: 'Phở Tái Nạm',
  category: 'phở',
  rating: 4.3,
  price: 30,
  img: 'img/phở/PhoTaiNam.png',
  quantity: 1,
},
];
export { foodItem };